### PR TITLE
week3 solutions updated

### PR DESCRIPTION
**Pull request by Felixyu007**

### CODE REVIEW

**Comment by Felixyu007** [comment]
Hi, Osama why you always close my pull request? I need to merge it

**Comment by 19921993** [comment]
I'm sorry i thought i did confirmed
tell which  button i should click

**Comment by 19921993** [comment]
[image: Screen Shot 2023-06-12 at 7.41.45 PM.png]

**Comment by Felixyu007** [comment]
You should review changes under "Files changed" then you can submit review with approve, then click Merge pull request

**Review by 19921993 — APPROVED** [review]

**Comment by 19921993** [comment]
done sorry about that

**Comment by Felixyu007** [comment]
No problem👍

**Pull request merged**
